apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kibana
spec:
  secretName: kibana-cert
  commonName: "kibana.talks.cloudnative.barcelona"
  dnsNames:
    - kibana.talks.cloudnative.barcelona
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
